# Basic I/O of DFPT
The density functional perturbation theory (DFPT) specific methods and attributes are available in 'crystal_io.py' since July 2022.

**Classes used in this tutorial are defined in 'CRYSTALpy.crystal_io'. Documentations and source codes are attached at the bottom of this page.**

## Tests

4 tests are performed. The first one is for $\Gamma$ point frequencies. The second one is for dispersion calculations. The third one has negative frequencies, in order to examine the method `clean_imaginary`. The last one is to illustrate the general applicability of this module to QHA outputs.

1. Form I paracetamol, 'freqf1-r0.out', $\Gamma$ point HA frequencies, with occasional warning messages. nqpoint = 1, nmode = 240, natom = 80.  
2. A graphene primitive cell, 'nostr-modes.out', phonon dispersion calculated along the $\Gamma-K-M$ path. nqpoint = 123, nmode = 6, natom = 2.  
3. Form II paracetamol, 'f2p2q-r1.out', $\Gamma$ point HA frequencies, with imaginary modes. nqpoint = 1, nmode = 480, natom = 160.  
4. Corundum, 'corundum.out', available on [crystal tutorial website](https://tutorials.crystalsolutions.eu/tutorials/Tutorial_QHA/AL2O3_SC30_QHA.out). Used to illustrate the structure of data when reading outputs by the QHA module of CRYSTAL. 

### Get energy, qpoints and frequencies at each qpoint

nqpoint = 1, nmode = 240 for paracetamol case, nqpoint = 123, nmode = 3 for graphene case. In both cases, nqpoint should be an integer and nmode should be a numpy array.

In [1]:
from CRYSTALpy.crystal_io import Crystal_output

paracetamol = Crystal_output()
paracetamol.read_cry_output('data/freqf1-r0.out')
paracetamol.get_mode()
print('Paracetamol EDFT:', paracetamol.edft[0])
print('Paracetamol qpoint:', paracetamol.nqpoint, paracetamol.qpoint)
print('Paracetamol modes:', len(paracetamol.nmode), paracetamol.nmode)

Paracetamol EDFT: -5402457.523570631
Paracetamol qpoint: 1 [[0. 0. 0.]]
Paracetamol modes: 1 [240]


In [2]:
graphene = Crystal_output()
graphene.read_cry_output('data/nostr_modes.out')
graphene.get_mode()
print('Graphene EDFT:', graphene.edft[0])
print('Graphene qpoints:', graphene.nqpoint)
print('Graphene modes:', len(graphene.nmode), graphene.nmode)

Graphene EDFT: -28768041.661716238
Graphene qpoints: 123
Graphene modes: 123 [6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 6 6]


### Get eigenvectors
Self.eigenvector should be a 1 (nqpoint) * 240 (nmode) * 80 (natom) * 3 (xyz) numpy array for paracetamol case. A 123 * 6 * 2 * 3 array for graphene case.

Example: Find the qpoint coordinate, frequency and eigenvectors of all atoms in the graphene primitive cell, with a given qpoint (75) and vibrational mode (3rd)

In [3]:
paracetamol.get_eigenvector()

print('Paracetamol')
print('nqpoint=', len(paracetamol.eigenvector),
      'nmode=', len(paracetamol.eigenvector[0]),
      'natom=', len(paracetamol.eigenvector[0, 0]),
      'first eigenvector=', paracetamol.eigenvector[0, 0, 0])

lattice = graphene.get_eigenvector()
print('Graphene')
print('nqpoint=', len(graphene.eigenvector),
      'nmode=', len(graphene.eigenvector[0]),
      'natom=', len(graphene.eigenvector[0, 0]),
      'first eigenvector=', graphene.eigenvector[0, 0, 0])


Paracetamol
nqpoint= 1 nmode= 240 natom= 80 first eigenvector= [ 0.11126206  0.         -0.01098885]
Graphene
nqpoint= 123 nmode= 6 natom= 2 first eigenvector= [ 0.         -0.          0.70710678]


In [4]:
print('Wavevector coordinates:', graphene.qpoint[74])
print('Frequency:', graphene.frequency[74, 2])
print('Eigenvectors:', graphene.eigenvector[74, 2])

Wavevector coordinates: [0.47083333 0.05833333 0.        ]
Frequency: 19.8656
Eigenvectors: [[ 3.49519213e-04  7.13019194e-01 -3.49519213e-04]
 [-3.49519213e-03  7.01135541e-01  3.49519213e-04]]


Compare with the crystal output file:

At the start point of $K-M$ path:  
```
 *******************************************************************************

  PHONONS ALONG PATH:   2 NUMBER OF K POINTS:   41

  FROM K  (   2   2   0 ) TO K  (   3   0   0 ) WITH DENOMINATOR    6

  THE POSITION OF THE POINTS IS EXPRESSED IN UNITS        OF DENOMINATOR  240

 *******************************************************************************
```
 
 At the 75th qpoint:  
```
 DISPERSION K POINT NUMBER    75 COORD:  C( 113  14   0 )    WEIGHT:    1.

    MODES         EIGV          FREQUENCIES     IRREP
             (HARTREE**2)   (CM**-1)     (THZ)
    1-   1    0.4928E-05    487.1942   14.6057  (  1)
    2-   2    0.8383E-05    635.4696   19.0509  (  1)
    3-   3    0.9116E-05    662.6443   19.8656  (  1)
    4-   4    0.3933E-04   1376.3503   41.2619  (  1)
    5-   5    0.4131E-04   1410.6170   42.2892  (  1)
    6-   6    0.4439E-04   1462.3150   43.8391  (  1)

 MODES IN PHASE

 FREQ(CM**-1)    487.19    635.47    662.64   1376.35   1410.62   1462.32

 AT.   1 C  X     0.0001    0.0001    0.0001   -0.2006    0.1997    0.0072
            Y     0.0000   -0.0001    0.2040    0.0015   -0.0002   -0.1963
            Z     0.2041   -0.2007   -0.0001    0.0001    0.0001    0.0000
 AT.   2 C  X    -0.0001    0.0001   -0.0010    0.2041    0.1963    0.0003
            Y     0.0000   -0.0001    0.2006   -0.0004   -0.0077    0.1996
            Z     0.2007    0.2041    0.0001    0.0001   -0.0001   -0.0000 
```


### Get rid of negative frequency
A test is performed on a harmonic phonon output with negative frequencies. In principle, the user is expected to redo all calculations to get rid of imaginary modes, instead of continuing thermodynamic analysis. Here we assume the user does not know the existance of imagninary modes.

Tests performed on Form II paracetamol $\Gamma$ point, stretched by 2% volumetric strain. There are 160 atoms, 480 modes, 1 qpoint. The output is attached in the same directory named as 'f2p2q-r1.out'. Modes 1-5 are negative, as given below:

```
    MODES         EIGV          FREQUENCIES     IRREP  IR   INTENS    RAMAN
             (HARTREE**2)   (CM**-1)     (THZ)             (KM/MOL)
    1-   1   -0.7201E-07    -58.8941   -1.7656  (B3g)   I (     0.00)   A
    2-   2   -0.6031E-07    -53.9001   -1.6159  (Ag )   I (     0.00)   A
    3-   3   -0.3525E-07    -41.2052   -1.2353  (Au )   I (     0.00)   I
    4-   4   -0.1932E-07    -30.5064   -0.9146  (B2g)   I (     0.00)   A
    5-   5   -0.2848E-08    -11.7124   -0.3511  (B1g)   I (     0.00)   A
    6-   6   -0.4132E-19      0.0000    0.0000  (B2u)   A (     0.00)   I
```

PS: Never use pob-TZVP basis set for energies, that is miserable :-)

In [5]:
neg_freq = Crystal_output()
neg_freq.read_cry_output('data/f2p2q-r1.out')
neg_freq.get_mode()
neg_freq.get_eigenvector()
neg_freq.clean_imaginary()

print(neg_freq.frequency[0, :6])
print(neg_freq.eigenvector[0, :6, 0, :])

[nan nan nan nan nan  0.]
[[        nan         nan         nan]
 [        nan         nan         nan]
 [        nan         nan         nan]
 [        nan         nan         nan]
 [        nan         nan         nan]
 [-0.07905694 -0.          0.        ]]


### Read outputs from QHA module

The QHA module of CRYSTAL includes automatic generation, optimization and frequency calculations at $\Gamma$ point. Therefore a different strategy is adopted and keeps the structure of code consistent. Since in all cases, nqpoint = 1, this dimension is removed to avoid an extra 'ncalc' dimension. `Crystal_output().frequency` becomes a 'ncalc\*nmode' list that corresponds to frequencies at each volume, or HA phonon calculation, instead of at each q point. Other attributes are changed accordingly.

In [7]:
qha_freq = Crystal_output()
qha_freq.read_cry_output('data/corundum.out')
qha_freq.get_mode()
qha_freq.get_eigenvector()

print(qha_freq.nqpoint)
print(qha_freq.qpoint)
print(qha_freq.nmode)

4
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[90 90 90 90]


## Class Crystal_output

Class Crystal_output can be used to extract the harmonic frequency calculation data from the output.

### Methods
#### `self.check_freq_file()`  
  
Check whether an output file is specified and whether it is a frequency calculation file. Not a standalone method. The identifier used: 
```
+++ SYMMETRY ADAPTION OF VIBRATIONAL MODES +++
```
No input, no output attribute.

In [ ]:
    """
    Thermodynamic-specific attributes, including:
        self.edft: get_qpoint, DFT total energy at central point, with probable
                   corrections. Unit: KJ / mol cell
        self.nqpoint: get_qpoint, Number of q points
        self.qpoint: get_qpoint, Fractional coordinates of qpoints
        self.nmode: get_mode, Number of vibrational modes at all qpoints
        self.frequency: get_mode, Frequencies of all modes at all qpoints.
                        Unit: THz
        self.eigenvector: get_eigenvector, Eigenvectors (classical amplitude)
                          of all atoms all modes at all qpoints. Unit: Angstrom
    """

    def check_freq_file(self):
        """
        Not a standalone method. Check if the output is specified and if it is
        a frequency output. The identifier:
        +++ SYMMETRY ADAPTION OF VIBRATIONAL MODES +++

        Input:
            -
        Output:
            is_freq: bool, True if the identifier is found.
        """
        import re
        import sys

        if not hasattr(self, 'data'):
            print('ERROR: Output file not specified.')
            sys.exit(1)

        is_freq = False

        for line in self.data:
            if re.match(r'^\s*\+\+\+\sSYMMETRY\sADAPTION\sOF\sVIBRATIONAL\sMODES\s\+\+\+', line):
                is_freq = True
                break
            else:
                continue

        return is_freq

#### `self.get_qpoint()`
  
Get DFT total energy of the system and the list of q points where the vibrational frequency is calculated. Dispersion output (multiple q points) is supported. 

To avoid ambigious definition, the search for DFT total energy is integrated into this method. To consider possible empirical corrections, the total energy reported at the central point when taking the numerical secondary derivatives is used, instead of the converged value at the final step of SCF.

No input.

Output attributes:
- `self.edft` DFT total energy. Unit: KJ / mol cell. Note: For harmonic calculations at $\Gamma$ and dispersion calculations, the length of `self.edft` is 1 * 1 since only 1 central calculation is performed. For QHA calculations, its length is nSampling point * 1 list.
- `self.nqpoint` Number of q points where the frequencies are calculated.
- `self.qpoint` Fractional coordinates of qpoints in the first Brillouin zone.

In [ ]:
    def get_qpoint(self):
        """
        Get the lattice information, DFT total energy and qpoints at which the
        phonon frequency is calculated.

        Note: edft is a list to make the script compatible with QHA output. The
              sampled HA calculations in QHA output are recognized as HA
              calculations at various qpoints. 

              For other cases, self.edft is an array of the same numbers,
              corresponding to the number of qpoints.

        Input:
            -
        Output:
            self.edft, nqpoint * 1 array, DFT total energy. Unit: KJ / mol cell
            self.nqpoint, int, Number of q points where the frequencies are
                          calculated.
            self.qpoint, nq * 3 numpy float array, Fractional coordinates of
                         qpoints.
        """
        import re
        import numpy as np
        import sys

        is_freq = self.check_freq_file()
        if not is_freq:
            print('ERROR: Not a frequency output.')
            sys.exit(1)

        edft = np.array([], dtype=float)
        self.nqpoint = 0
        self.qpoint = np.array([], dtype=float)

        for i, line in enumerate(self.data):
# Keywords in gradient calculation
            if re.match(r'\s*CENTRAL POINT', line):
                edft = np.append(edft, float(line.strip().split()[2]) * 2625.500256)

            if re.search(r'EXPRESSED IN UNITS\s*OF DENOMINATOR', line):
                shrink = int(line.strip().split()[-1])

# Keywords in dipersion calculation
            if re.match(r'\s*DISPERSION K POINT NUMBER', line):
                coord = np.array(line.strip().split()[7:10], dtype=float)
                self.qpoint = np.append(self.qpoint, coord / shrink)
                self.nqpoint += 1

# HA Gamma point calculation
        if self.nqpoint == 0 and len(edft) == 1:
            self.nqpoint = 1
            self.qpoint = np.array([[0, 0, 0]], dtype=float)
            self.edft = edft
# QHA Gamma point calculation
        elif self.nqpoint == 0 and len(edft) > 1:
            self.nqpoint = len(edft)
            self.qpoint = np.array([[0, 0, 0] for i in range(self.nqpoint)], dtype=float)
# HA dispersion calculation
        elif self.nqpoint > 0 and len(edft) == 1:
            self.qpoint = np.reshape(self.qpoint, (-1, 3))
            self.edft = edft
        else:
            print('ERROR: Only support: 1. HA, Gamma point 2. QHA, gamma point 3. HA dispersion.')
            sys.exit(1)

        return self.edft, self.nqpoint, self.qpoint

#### `self.get_mode()`
Get frequencies of all modes at all the q points sampled and compute the total number of vibration modes (natoms * 3).

No input. 

Output attributes:
- `self.nmode` Number of vibration modes at each qpoint
- `self.frequency` Harmonic vibrational frequency $\nu$. Unit: THz

Note: 

Angular frequency: $\omega = 2\pi\nu$  
Eigen value of dynamic matrix: $\lambda = \nu^{2}$

In [ ]:
    def get_mode(self):
        """
        Get corresponding vibrational frequencies and for all modes and
        compute the total number of vibration modes (natoms * 3).

        Input:
            -
        Output:
            self.nmode, nqpoint * 1 numpy int array, Number of vibration modes
                        at each qpoints.
            self.frequency: nqpoint * nmode numpy float array, Harmonic
                            vibrational frequency. Unit: THz
        """
        import numpy as np
        import re

        if not hasattr(self, 'nqpoint'):
            self.get_qpoint()

        self.frequency = np.array([], dtype=float)

        countline = 0
        while countline < len(self.data):
            is_freq = False
            if re.match(r'\s*DISPERSION K POINT NUMBER\s*\d',
                        self.data[countline]):
                countline += 2
                is_freq = True

            if re.match(r'\s*MODES\s*EIGV\s*FREQUENCIES\s*IRREP',
                        self.data[countline]):
                countline += 2
                is_freq = True

            while self.data[countline].strip() and is_freq:
                line_data = re.findall(r'\-*[\d\.]+[E\d\-\+]*',
                                       self.data[countline])
                if line_data:
                    nm_a = int(line_data[0].strip('-'))
                    nm_b = int(line_data[1])
                    freq = float(line_data[4])

                for mode in range(nm_a, nm_b + 1):
                    self.frequency = np.append(self.frequency, freq)

                countline += 1

            countline += 1

        self.frequency = np.reshape(self.frequency, (self.nqpoint, -1))
        self.nmode = np.array([len(i) for i in self.frequency], dtype=int)

        return self.nmode, self.frequency

#### `self.get_eigenvector()`
Get the eigenvectors of all normal modeson all the atoms in the supercell. Eigenvectors are normalised to classical amplitudes. 

No input. Output attributes:
- `self.eigenvector` Eigenvectors expressed in Cartesian coordinate, at all atoms, all modes and all qpoints. Classical amplitude(298.15K). Unit: Angstrom

In [ ]:
    def get_eigenvector(self):
        """
        Get corresponding mode eigenvectors for all modes on all
        atoms in the supercell.

        Input:
            -
        Output:
            self.eigenvector, nqpoint * nmode * natom * 3 numpy float array,
                              Eigenvectors expressed in Cartesian coordinate,
                              at all atoms, all modes and all qpoints.
                              Classical amplitude. Unit: Angstrom
        """
        import numpy as np
        import re

        if not hasattr(self, 'nmode'):
            self.get_mode()

        total_mode = np.sum(self.nmode)
        countline = 0
        # Multiple blocks for 1 mode. Maximum 6 columns for 1 block.
        if np.max(self.nmode) >= 6:
            countmode = 6
        else:
            countmode = total_mode

        # Read the eigenvector region as its original shape
        block_label = False
        total_data = []
        while countline < len(self.data) and countmode <= total_mode:
            # Gamma point / phonon dispersion calculation
            if re.match(r'\s*MODES IN PHASE', self.data[countline]) or\
               re.match(r'\s*NORMAL MODES NORMALIZED', self.data[countline]):
                block_label = True
            elif re.match(r'\s*MODES IN ANTI-PHASE', self.data[countline]):
                block_label = False

            # Enter a block
            if re.match(r'\s*FREQ\(CM\*\*\-1\)', self.data[countline]) and\
               block_label:
                countline += 2
                block_data = []
                while self.data[countline].strip():
                    # Trim annotation part (12 characters)
                    line_data = re.findall(r'\-*[\d\.]+[E\d\-\+]*',
                                           self.data[countline][13:])
                    if line_data:
                        block_data.append(line_data)

                    countline += 1

                countmode += len(line_data)
                total_data.append(block_data)

            countline += 1

        total_data = np.array(total_data, dtype=float)

        # Rearrage eigenvectors
        block_per_q = len(total_data) / self.nqpoint
        self.eigenvector = []
        # 1st dimension, nqpoint
        for q in range(self.nqpoint):
            index_bg = int(q * block_per_q)
            index_ed = int((q + 1) * block_per_q)
            q_data = np.hstack([i for i in total_data[index_bg: index_ed]])
        # 2nd dimension, nmode
            q_data = np.transpose(q_data)
        # 3rd dimension, natom
            natom = int(self.nmode[q] / 3)
            q_rearrange = [np.split(m, natom, axis=0) for m in q_data]

            self.eigenvector.append(q_rearrange)

        self.eigenvector = np.array(self.eigenvector)
        
        # Normalize eigenvectors of each mode to 1
        for idx_q, q in enumerate(self.eigenvector):
            for idx_m, m in enumerate(q):
                self.eigenvector[idx_q, idx_m] = \
                    self.eigenvector[idx_q, idx_m] / np.linalg.norm(m)

        return self.eigenvector

#### `clean_imaginary()`
Not a standalone method. Used after get_mode(). Substitute the negative frequencies with numpy NaN values and keep the original shape of numpy arrays. The threshold of a negative frequency is -0.0001 THz.

No input. No output attributes.

In [ ]:
    def clean_imaginary(self):
        """
        Substitute imaginary modes and corresponding eigenvectors with numpy
        NaN format and print warning message.

        Input:
            -
        Output:
            cleaned attributes.
            self.frequency
            self.eigenvector
        """
        import numpy as np

        for q, freq in enumerate(self.frequency):
            if freq[0] > -1e-4:
                continue

            print(
                'WARNING: Negative frequencies detected - Calculated thermodynamics might be inaccurate.')
            print('WARNING: Negative frequencies will be substituted by NaN.')

            neg_rank = np.where(freq <= -1e-4)[0]
            self.frequency[q, neg_rank] = np.nan

            if hasattr(self, 'eigenvector'):
                natom = int(self.nmode[q] / 3)
                nan_eigvt = np.full([natom, 3], np.nan)
                self.eigenvector[q, neg_rank] = nan_eigvt

        if hasattr(self, 'eigenvector'):
            return self.frequency, self.eigenvector
        else:
            return self.frequency