# Unit tests notebook

# file_readwrite

### Crystal_input

In [2]:
import sys
sys.path.insert(1,'../crystal_functions/')
from unit_test import *
import pandas as pd
#from crystal_functions.unit_test import *

input_test = crystal_input_test('./data_test/')

pd.DataFrame(input_test[1],input_test[0])

File for input testing: ./data_test/mgo.d12


0
geom_block  True
bs_block    True
func_block  True
scf_block   True
add_ghost   True
sp_to_opt   True
opt_to_sp   True

### Crystal_output

In [1]:
import sys
sys.path.insert(1,'../crystal_functions/')
from unit_test import *
import pandas as pd

output_test = crystal_output_test('./data_test/')

pd.DataFrame(output_test[1],output_test[0])

File for input testing: ./data_test/mgo.out


0
converged               True
get_dimensionality      True
get_final_energy        True
get_scf_convergence     True
get_num_cycles          True
get_fermi_energy        True
get_primitive_lattice   True
get_reciprocal_lattice  True
get_band_gap            True
get_last_geom           True
get_symm_ops            True
get_forces              True
get_mulliken_charges    True

# convert

In [1]:
import sys
sys.path.insert(1,'../crystal_functions/')
from unit_test import *
import pandas as pd

output_test = convert_test('./data_test/')

pd.DataFrame(output_test[1],output_test[0])

[[0.         2.12011001 2.12011001]
 [2.12011001 0.         2.12011001]
 [2.12011001 2.12011001 0.        ]]
[[-1.29819297e-16  2.12011001e+00  2.12011001e+00]
 [ 2.12011001e+00  0.00000000e+00  2.12011001e+00]
 [ 2.12011001e+00  2.12011001e+00  2.59638594e-16]]


0
cry_out2pmg  True
cry_gui2pmg  True

In [4]:

import numpy as np
a = np.array([[0.    , 2.1085, 2.1085],
       [2.1085, 0.    , 2.1085],
       [2.1085, 2.1085, 0.    ]])
b = np.array([[0.    , 2.1085, 2.1085],
       [2.1085, 0.    , 2.1085],
       [2.1085, 2.1085, 0.    ]])

np.all(a == b)

True

In [8]:
from crystal_functions.file_readwrite import Crystal_input
tst = Crystal_input('./data_test/mgo.d12')
tst.sp_to_opt()
tst.opt_to_sp()
tst.geom_block

['MGO BULK - GEOMETRY TEST\n',
 'CRYSTAL\n',
 '0 0 0\n',
 '225\n',
 '4.217\n',
 '2\n',
 '12 0.    0.    0.\n',
 '8 0.5   0.5   0.5\n',
 'END\n']