# Example notebook for the functions contained in cry_calculate.py

### Calculate the BSSE

In [2]:
from crystal_functions.calculate import cry_bsse

ImportError: cannot import name 'cry_bsse' from 'crystal_functions.calculate' (/Users/brunocamino/miniconda3/envs/test_env/lib/python3.9/site-packages/crystal_functions/calculate.py)

### Generate a pymatgen structure (substrate+adsorbate)

In [3]:
import sys
sys.path.insert(1, '../')

from pymatgen.core import Structure, Lattice
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.core.surface import SlabGenerator

#from cry_file_readwrite import write_gui 
import numpy as np

substrate = Structure.from_spacegroup("Fm-3m", Lattice.cubic(3.597), ["Cu"], [[0, 0, 0]])
substrate = SpacegroupAnalyzer(substrate).get_conventional_standard_structure()
substrate = SpacegroupAnalyzer(substrate).get_symmetrized_structure()


slab = SlabGenerator(substrate, (1,0,0), 5., 10., center_slab=True).get_slab()
substrate.atomic_numbers

<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject


(29, 29, 29, 29)

In [4]:
n_symmops = len(SpacegroupAnalyzer(substrate).get_space_group_operations())
print(n_symmops/4)
print(SpacegroupAnalyzer(substrate).get_point_group_operations(cartesian=True)[3])
print(np.array(SpacegroupAnalyzer(substrate).get_point_group_operations(cartesian=True)[3].as_dict()['matrix']))
np.array(SpacegroupAnalyzer(substrate).get_point_group_operations(cartesian=True)[3].as_dict()['matrix'])[0:4,0:3]

48.0
Rot:
[[ 6.1232340e-17  1.0000000e+00  0.0000000e+00]
 [-1.0000000e+00 -6.1232340e-17  0.0000000e+00]
 [-2.1890417e-33  1.2246468e-16 -1.0000000e+00]]
tau
[0. 0. 0.]
[[ 6.1232340e-17  1.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.0000000e+00 -6.1232340e-17  0.0000000e+00  0.0000000e+00]
 [-2.1890417e-33  1.2246468e-16 -1.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00]]


array([[ 6.1232340e-17,  1.0000000e+00,  0.0000000e+00],
       [-1.0000000e+00, -6.1232340e-17,  0.0000000e+00],
       [-2.1890417e-33,  1.2246468e-16, -1.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00]])

In [17]:
for i in range(len(SpacegroupAnalyzer(substrate).get_space_group_operations())):
    for symmops in np.array(SpacegroupAnalyzer(substrate).get_point_group_operations(cartesian=True)[i].as_dict()['matrix'])[0:4,0:3]:    
        print('{}\n'.format(' '.join(str(np.around(n,8)) for n in symmops)))

1.0 0.0 0.0

0.0 1.0 0.0

0.0 -0.0 1.0

0.0 0.0 0.0

-1.0 0.0 0.0

0.0 -1.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

-0.0 -1.0 0.0

1.0 0.0 0.0

0.0 -0.0 1.0

0.0 0.0 0.0

0.0 1.0 0.0

-1.0 -0.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

-1.0 0.0 0.0

0.0 -1.0 0.0

-0.0 -0.0 1.0

0.0 0.0 0.0

1.0 0.0 0.0

0.0 1.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

0.0 1.0 0.0

-1.0 -0.0 0.0

-0.0 -0.0 1.0

0.0 0.0 0.0

-0.0 -1.0 0.0

1.0 0.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

1.0 0.0 0.0

0.0 -1.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

-1.0 -0.0 0.0

0.0 1.0 0.0

-0.0 -0.0 1.0

0.0 0.0 0.0

0.0 -1.0 0.0

-1.0 -0.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

-0.0 1.0 0.0

1.0 0.0 0.0

0.0 -0.0 1.0

0.0 0.0 0.0

-1.0 -0.0 0.0

0.0 1.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

1.0 0.0 0.0

0.0 -1.0 0.0

0.0 -0.0 1.0

0.0 0.0 0.0

-0.0 1.0 0.0

1.0 0.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

0.0 -1.0 0.0

-1.0 -0.0 0.0

-0.0 -0.0 1.0

0.0 0.0 0.0

-0.0 -0.0 1.0

1.0 0.0 0.0

0.0 1.0 0.0

0.0 0.0 0.0

0.0 0.0 -1.0

-1.0 -0.0 0.0

-0.0 -1.0 -0.0

0.0 0.0 0.0

-0.0 -0.0 

1.0 0.0 0.0

0.0 1.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

0.0 1.0 0.0

-1.0 -0.0 0.0

-0.0 -0.0 1.0

0.0 0.0 0.0

-0.0 -1.0 0.0

1.0 0.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

1.0 0.0 0.0

0.0 -1.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

-1.0 -0.0 0.0

0.0 1.0 0.0

-0.0 -0.0 1.0

0.0 0.0 0.0

0.0 -1.0 0.0

-1.0 -0.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

-0.0 1.0 0.0

1.0 0.0 0.0

0.0 -0.0 1.0

0.0 0.0 0.0

-1.0 -0.0 0.0

0.0 1.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

1.0 0.0 0.0

0.0 -1.0 0.0

0.0 -0.0 1.0

0.0 0.0 0.0

-0.0 1.0 0.0

1.0 0.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

0.0 -1.0 0.0

-1.0 -0.0 0.0

-0.0 -0.0 1.0

0.0 0.0 0.0

-0.0 -0.0 1.0

1.0 0.0 0.0

0.0 1.0 0.0

0.0 0.0 0.0

0.0 0.0 -1.0

-1.0 -0.0 0.0

-0.0 -1.0 -0.0

0.0 0.0 0.0

-0.0 -0.0 1.0

0.0 -1.0 0.0

1.0 0.0 0.0

0.0 0.0 0.0

0.0 0.0 -1.0

0.0 1.0 0.0

-1.0 0.0 -0.0

0.0 0.0 0.0

0.0 -0.0 1.0

-1.0 -0.0 0.0

-0.0 -1.0 0.0

0.0 0.0 0.0

0.0 0.0 -1.0

1.0 0.0 0.0

0.0 1.0 -0.0

0.0 0.0 0.0

-0.0 -0.0 1.0

0.0 1.0 0.0

-1.0 0.0 0.0

0.0 0.0 0.0

0.0 0.0 