# Example notebook for the functions contained in cry_calculate.py

### Calculate the BSSE

In [1]:
import sys
sys.path.insert(1, '../')

from cry_calculate import cry_bsse

### Generate a pymatgen structure (substrate+adsorbate)

In [21]:
import sys
sys.path.insert(1, '../')

from pymatgen.core import Structure, Lattice
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.core.surface import SlabGenerator

#from cry_file_readwrite import write_gui 
import numpy as np

substrate = Structure.from_spacegroup("Fm-3m", Lattice.cubic(3.597), ["Cu"], [[0, 0, 0]])
substrate = SpacegroupAnalyzer(substrate).get_conventional_standard_structure()
substrate = SpacegroupAnalyzer(substrate).get_symmetrized_structure()


slab = SlabGenerator(substrate, (1,0,0), 5., 10., center_slab=True).get_slab()
substrate.atomic_numbers

[[PeriodicSite: Cu (0.0000, 0.0000, 0.0000) [0.0000, 0.0000, 0.0000],
  PeriodicSite: Cu (-0.0000, 1.7985, 1.7985) [0.0000, 0.5000, 0.5000],
  PeriodicSite: Cu (1.7985, 0.0000, 1.7985) [0.5000, 0.0000, 0.5000],
  PeriodicSite: Cu (1.7985, 1.7985, 0.0000) [0.5000, 0.5000, 0.0000]]]

In [38]:
n_symmops = len(SpacegroupAnalyzer(substrate).get_space_group_operations())
print(n_symmops/4)
print(SpacegroupAnalyzer(substrate).get_point_group_operations(cartesian=True)[3])
print(np.array(SpacegroupAnalyzer(substrate).get_point_group_operations(cartesian=True)[3].as_dict()['matrix']))
np.array(SpacegroupAnalyzer(substrate).get_point_group_operations(cartesian=True)[3].as_dict()['matrix'])[0:4,0:3]

48.0
Rot:
[[ 6.1232340e-17  1.0000000e+00  0.0000000e+00]
 [-1.0000000e+00 -6.1232340e-17  0.0000000e+00]
 [ 0.0000000e+00  1.2246468e-16 -1.0000000e+00]]
tau
[0. 0. 0.]
[[ 6.1232340e-17  1.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.0000000e+00 -6.1232340e-17  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  1.2246468e-16 -1.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00]]


array([[ 6.1232340e-17,  1.0000000e+00,  0.0000000e+00],
       [-1.0000000e+00, -6.1232340e-17,  0.0000000e+00],
       [ 0.0000000e+00,  1.2246468e-16, -1.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00]])

In [17]:
for i in range(len(SpacegroupAnalyzer(substrate).get_space_group_operations())):
    for symmops in np.array(SpacegroupAnalyzer(substrate).get_point_group_operations(cartesian=True)[i].as_dict()['matrix'])[0:4,0:3]:    
        print('{}\n'.format(' '.join(str(np.around(n,8)) for n in symmops)))

1.0 0.0 0.0

0.0 1.0 0.0

0.0 -0.0 1.0

0.0 0.0 0.0

-1.0 0.0 0.0

0.0 -1.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

-0.0 -1.0 0.0

1.0 0.0 0.0

0.0 -0.0 1.0

0.0 0.0 0.0

0.0 1.0 0.0

-1.0 -0.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

-1.0 0.0 0.0

0.0 -1.0 0.0

-0.0 -0.0 1.0

0.0 0.0 0.0

1.0 0.0 0.0

0.0 1.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

0.0 1.0 0.0

-1.0 -0.0 0.0

-0.0 -0.0 1.0

0.0 0.0 0.0

-0.0 -1.0 0.0

1.0 0.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

1.0 0.0 0.0

0.0 -1.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

-1.0 -0.0 0.0

0.0 1.0 0.0

-0.0 -0.0 1.0

0.0 0.0 0.0

0.0 -1.0 0.0

-1.0 -0.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

-0.0 1.0 0.0

1.0 0.0 0.0

0.0 -0.0 1.0

0.0 0.0 0.0

-1.0 -0.0 0.0

0.0 1.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

1.0 0.0 0.0

0.0 -1.0 0.0

0.0 -0.0 1.0

0.0 0.0 0.0

-0.0 1.0 0.0

1.0 0.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

0.0 -1.0 0.0

-1.0 -0.0 0.0

-0.0 -0.0 1.0

0.0 0.0 0.0

-0.0 -0.0 1.0

1.0 0.0 0.0

0.0 1.0 0.0

0.0 0.0 0.0

0.0 0.0 -1.0

-1.0 -0.0 0.0

-0.0 -1.0 -0.0

0.0 0.0 0.0

-0.0 -0.0 

1.0 0.0 0.0

0.0 1.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

0.0 1.0 0.0

-1.0 -0.0 0.0

-0.0 -0.0 1.0

0.0 0.0 0.0

-0.0 -1.0 0.0

1.0 0.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

1.0 0.0 0.0

0.0 -1.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

-1.0 -0.0 0.0

0.0 1.0 0.0

-0.0 -0.0 1.0

0.0 0.0 0.0

0.0 -1.0 0.0

-1.0 -0.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

-0.0 1.0 0.0

1.0 0.0 0.0

0.0 -0.0 1.0

0.0 0.0 0.0

-1.0 -0.0 0.0

0.0 1.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

1.0 0.0 0.0

0.0 -1.0 0.0

0.0 -0.0 1.0

0.0 0.0 0.0

-0.0 1.0 0.0

1.0 0.0 0.0

0.0 0.0 -1.0

0.0 0.0 0.0

0.0 -1.0 0.0

-1.0 -0.0 0.0

-0.0 -0.0 1.0

0.0 0.0 0.0

-0.0 -0.0 1.0

1.0 0.0 0.0

0.0 1.0 0.0

0.0 0.0 0.0

0.0 0.0 -1.0

-1.0 -0.0 0.0

-0.0 -1.0 -0.0

0.0 0.0 0.0

-0.0 -0.0 1.0

0.0 -1.0 0.0

1.0 0.0 0.0

0.0 0.0 0.0

0.0 0.0 -1.0

0.0 1.0 0.0

-1.0 0.0 -0.0

0.0 0.0 0.0

0.0 -0.0 1.0

-1.0 -0.0 0.0

-0.0 -1.0 0.0

0.0 0.0 0.0

0.0 0.0 -1.0

1.0 0.0 0.0

0.0 1.0 -0.0

0.0 0.0 0.0

-0.0 -0.0 1.0

0.0 1.0 0.0

-1.0 0.0 0.0

0.0 0.0 0.0

0.0 0.0 